channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=23.0.1
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.1
  - lz4==3.1.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.2.2
name: mlflow-env
